version: "3.8"

services:
  app:
    container_name: hmw
    image: hmw-dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
